/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness */
        get: operations["GetHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lifetime stats for the authenticated agent (tickets created, reviews approved/rejected). For gamification. */
        get: operations["GetMeStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/stats/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily activity counts for the last N days (for activity graph). Oldest day first. */
        get: operations["GetMeStatsHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations for the authenticated user (OAuth required) */
        get: operations["ListOrgs"];
        put?: never;
        /** Create organization (auth required) */
        post: operations["CreateOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgID}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListProjectsByOrg"];
        put?: never;
        post: operations["CreateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update project (e.g. set status to active or closed) */
        patch: operations["UpdateProject"];
        trace?: never;
    };
    "/projects/{projectID}/work-streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListWorkStreams"];
        put?: never;
        post: operations["CreateWorkStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/work-streams/{workStreamID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetWorkStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdateWorkStream"];
        trace?: never;
    };
    "/projects/{projectID}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTickets"];
        put?: never;
        post: operations["CreateTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdateTicket"];
        trace?: never;
    };
    "/projects/{projectID}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListPendingReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Execution trace (steps logged by the agent while working) */
        get: operations["GetTrace"];
        put?: never;
        /** Append a step to the execution trace (requires valid lease) */
        post: operations["LogStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State transition history for a ticket (timeline of state changes) */
        get: operations["GetTransitions"];
        put?: never;
        /** Transition ticket state (e.g. start, submit, approve, reject) */
        post: operations["TransitionTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListEscalations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/escalations/{escalationID}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResolveEscalation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/queue/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClaimTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/lease/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RenewLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ReleaseLease"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gate/callback/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive a webhook callback that satisfies a gate condition */
        post: operations["PostGateCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tracked Claude Code and Codex sessions */
        get: operations["ListSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/collector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health of the session ingestion loop */
        get: operations["GetSessionCollectorStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session detail with prompts, links, and subagent children */
        get: operations["GetSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionID}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link a session to a PR, Linear issue, ticket, or review */
        post: operations["CreateSessionLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linear/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health of the Linear sync and the linked projects */
        get: operations["GetLinearStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/linear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Linear project this Flywheel project mirrors, if any */
        get: operations["GetProjectLinearLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/linear/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pull updated Linear issues for this project now */
        post: operations["SyncProjectLinear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List PR review requests */
        get: operations["ListCodeReviews"];
        put?: never;
        /** Queue reviews for the PR URLs or owner/repo#N references in the text */
        post: operations["CreateCodeReviews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-reviews/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review queue and watcher health */
        get: operations["GetCodeReviewStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-reviews/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews that landed on your own PRs */
        get: operations["ListFeedbackRounds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-reviews/feedback/{roundID}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a landed review as addressed or ignored */
        post: operations["SetFeedbackRoundState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-reviews/feedback/{roundID}/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the feedback harness on the PR branch to resolve a landed review */
        post: operations["AddressFeedbackRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-reviews/{reviewID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review request detail with findings */
        get: operations["GetCodeReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-reviews/{reviewID}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue another review attempt */
        post: operations["RerunCodeReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-reviews/{reviewID}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop watching a PR */
        post: operations["CloseCodeReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeStats: {
            /** @description Total tickets created by this agent */
            tickets_created: number;
            /** @description Total reviews approved by this agent */
            reviews_approved: number;
            /** @description Total reviews rejected by this agent */
            reviews_rejected: number;
        };
        MeStatsHistory: {
            /** @description Date strings (YYYY-MM-DD) oldest first */
            days: string[];
            /** @description Ticket count per day */
            tickets_created: number[];
            reviews_approved: number[];
            reviews_rejected: number[];
        };
        StructuredError: {
            error: string;
            /** @enum {string} */
            code: "lease_expired" | "unauthorized" | "not_found" | "conflict" | "invalid_input" | "forbidden" | "internal" | "not_implemented" | "project_closed";
            retriable: boolean;
        };
        /** @description Returned when server cannot access repo (e.g. git-notes without repo_path) */
        NotImplementedError: {
            error?: string;
            /** @enum {string} */
            code?: "not_implemented";
        };
        LogStepRequest: {
            lease_token: string;
            step: components["schemas"]["TraceStepInput"];
        };
        TraceStepInput: {
            /** @enum {string} */
            type: "tool_call" | "observation" | "thought" | "error";
            payload?: Record<string, never>;
        };
        TransitionRequest: {
            trigger: string;
            actor_id?: string;
            /** @enum {string} */
            actor?: "human" | "agent" | "system";
            payload?: Record<string, never>;
        };
        Org: {
            id?: string;
            name?: string;
            slug?: string;
            /** Format: date-time */
            created_at?: string;
        };
        CreateOrgRequest: {
            name?: string;
            slug?: string;
        };
        Project: {
            id?: string;
            org_id?: string;
            name?: string;
            slug?: string;
            /** @description Short project description. */
            description?: string;
            repo_url?: string;
            /** @description Branch to checkout when closing a work stream; default "main". */
            default_branch?: string;
            tech_stack?: string[];
            context_pack?: Record<string, never>;
            /**
             * @description active (default) or closed; list endpoints default to active only.
             * @enum {string}
             */
            status?: "active" | "closed";
            /** @description Whether the dispatcher picks up tickets for this project (default true). */
            dispatch_enabled?: boolean;
            dispatch_config?: components["schemas"]["DispatchConfig"];
            /** Format: date-time */
            created_at?: string;
        };
        UpdateProjectRequest: {
            /** @enum {string} */
            status?: "active" | "closed";
            /** @description Project display name. */
            name?: string;
            /** @description Short project description. */
            description?: string;
            /** @description URL-safe identifier (unique per org). */
            slug?: string;
            /** @description Git repo URL; when set, enables work streams + git integration (branch instructions in MCP). */
            repo_url?: string;
            /** @description Branch to checkout when closing a work stream; default "main". */
            default_branch?: string;
            /** @description Whether the dispatcher picks up tickets for this project (default true). Takes effect immediately. */
            dispatch_enabled?: boolean;
            dispatch_config?: components["schemas"]["DispatchConfig"];
            /** @description Project context pack (system_prompt, conventions, key_files). */
            context_pack?: {
                system_prompt?: string;
                conventions?: string;
                key_files?: {
                    path?: string;
                    snippet?: string;
                }[];
            };
        };
        DispatchConfig: {
            /** @description Maximum concurrent active workers for this project. Set 0 or omit to inherit the server DISPATCH_MAX_WORKERS default. */
            max_active_workers?: number;
            /** @description Custom dispatch roles. Each role has its own routing policy and inherits prompt/tool behavior from a built-in worker type. */
            roles?: components["schemas"]["DispatchWorkerRole"][];
            workers?: components["schemas"]["DispatchWorkerProfile"][];
            policies?: {
                [key: string]: components["schemas"]["DispatchRolePolicy"];
            };
        };
        DispatchWorkerRole: {
            /** @description Stable custom role key used in dispatch policies and ticket inputs. */
            id?: string;
            name?: string;
            /** @description Additional instructions appended to workers launched for this custom role. */
            description?: string;
            /**
             * @description Built-in worker behavior this custom role inherits for prompts and tool access.
             * @enum {string}
             */
            base_type?: "planner" | "executor" | "validator" | "deployer" | "investigator";
        };
        DispatchWorkerProfile: {
            id?: string;
            name?: string;
            enabled?: boolean;
            /** @enum {string} */
            runner?: "cli" | "docker" | "openai-responses" | "openai-compatible";
            /** @enum {string} */
            driver?: "claude" | "generic";
            /** @description Override binary path when using a CLI or Docker-backed worker. */
            cli_path?: string;
            /** @description Model override for API-native workers. */
            model?: string;
            /** @description Reasoning effort override for API-native workers. */
            reasoning_effort?: string;
            /** @description Base URL override for API-native workers. */
            api_base_url?: string;
            /** @description Environment variable that holds the provider credential for this worker profile. */
            credential_env_var?: string;
            args?: string[];
        };
        DispatchRolePolicy: {
            /**
             * @description ordered tries workers in the configured order; any rotates across the configured workers.
             * @enum {string}
             */
            selection_mode?: "ordered" | "any";
            /** @description Worker profile IDs to use for this role. Leave empty to use all enabled workers. */
            worker_ids?: string[];
        };
        WorkStream: {
            id?: string;
            project_id?: string;
            name?: string;
            slug?: string;
            /** @description Markdown implementation plan (GFM, fenced code, Mermaid diagrams). */
            plan?: string;
            branch?: string;
            /** @enum {string} */
            status?: "active" | "closed";
            /** Format: date-time */
            created_at?: string;
        };
        CreateWorkStreamRequest: {
            name: string;
            slug?: string;
            /** @description Optional Markdown plan body. */
            plan?: string;
        };
        UpdateWorkStreamRequest: {
            name?: string;
            /** @description Markdown plan; send empty string to clear. */
            plan?: string;
            branch?: string;
            /** @enum {string} */
            status?: "active" | "closed";
        };
        CreateProjectRequest: {
            name?: string;
            slug?: string;
            repo_url?: string;
            tech_stack?: string[];
            /** @description Project template ID to seed from */
            template_id?: string;
            /** @description Which workstream templates to include. If omitted with template_id, all template workstreams are included. */
            work_stream_template_ids?: string[];
        };
        Objective: {
            description?: string;
            success_criteria?: string[];
            acceptance_test?: string;
        };
        TicketContext: {
            relevant_files?: string[];
            constraints?: string[];
            prior_attempts?: Record<string, never>[];
            human_answers?: string[];
        };
        Ticket: {
            id?: string;
            project_id?: string;
            title?: string;
            /** @enum {string} */
            type?: "task" | "bug" | "spike" | "review";
            priority?: number;
            /** @enum {string} */
            state?: "draft" | "planning" | "awaiting_input" | "executing" | "awaiting_validation" | "validated" | "closed";
            version?: number;
            objective?: components["schemas"]["Objective"];
            ticket_context?: components["schemas"]["TicketContext"];
            inputs?: Record<string, never>;
            outputs?: Record<string, never>;
            depends_on?: string[];
            work_stream_id?: string;
            /** @description Compound environment ID (spec v0.2 section 4.1) */
            environment_id?: string;
            /** @description Repository alias for multi-repo projects (from project_repositories). Empty means primary repo. */
            target_repo?: string;
            assigned_to?: string;
            /** @description Active workflow definition ID. Empty means legacy state machine. */
            workflow_id?: string;
            /** @description Current phase ID within the workflow. Empty means no active phase. */
            workflow_phase?: string;
            created_by?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            external?: components["schemas"]["TicketExternalRef"];
        };
        /** @description Projection of the external tracker issue (Linear) this ticket mirrors. */
        TicketExternalRef: {
            provider: string;
            external_id: string;
            /** @description e.g. RLETD-465 */
            identifier: string;
            url?: string;
            state_name?: string;
            /** @description triage, backlog, unstarted, started, completed, or canceled */
            state_type?: string;
            assignee?: string;
            team_key?: string;
            /** @description Linear priority 0 (none) to 4 (low) */
            priority: number;
            labels?: string[];
            branch_name?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            synced_at: string;
        };
        ProjectRepository: {
            id?: string;
            project_id?: string;
            /** @description Unique alias within the project (e.g. "backend", "frontend") */
            alias?: string;
            /** @description Git clone URL */
            repo_url?: string;
            /** @description Default branch name (e.g. "main") */
            default_branch?: string;
            /** @description Whether this is the primary repository */
            is_primary?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        CreateTicketRequest: {
            title: string;
            work_stream_id?: string;
            /** @description Repository alias for multi-repo projects (optional) */
            target_repo?: string;
            /** @enum {string} */
            type?: "task" | "bug" | "spike" | "review";
            priority?: number;
            created_by: string;
            depends_on?: string[];
            objective?: components["schemas"]["Objective"];
            ticket_context?: components["schemas"]["TicketContext"];
            /** @description Optional. Duplicate requests with the same key return the existing ticket. */
            idempotency_key?: string;
        };
        UpdateTicketRequest: {
            depends_on?: string[];
            /** @description When set, replaces the ticket title. */
            title?: string;
            /** @description Partial update; only fields present in the body are merged into the existing objective. Task/bug tickets must still have at least one of success_criteria or acceptance_test after the merge. */
            objective?: components["schemas"]["Objective"];
        };
        CreateReviewRequest: {
            /**
             * @description approved moves awaiting_validation → validated; rejected moves awaiting_validation → executing; reopened moves closed → draft (re-opens ticket for new lifecycle).
             * @enum {string}
             */
            decision: "approved" | "rejected" | "reopened";
            notes?: string;
            reviewer_id?: string;
        };
        ExecutionTrace: {
            ticket_id?: string;
            agent_id?: string;
            steps?: components["schemas"]["TraceStep"][];
            /** @description Total number of steps for this ticket (present when paginated) */
            total_count?: number;
        };
        TraceStep: {
            id?: string;
            /** @enum {string} */
            type?: "tool_call" | "observation" | "thought" | "error";
            payload?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
        };
        PendingReviewsResponse: {
            tickets?: components["schemas"]["Ticket"][];
        };
        Escalation: {
            id?: string;
            ticket_id?: string;
            agent_id?: string;
            reason?: string;
            question?: string;
            answer?: string;
            resolved_by?: string;
            /** Format: date-time */
            resolved_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ResolveEscalationRequest: {
            answer: string;
            reviewer_id?: string;
        };
        ClaimRequest: {
            agent_id: string;
            priority?: number;
            /** @description Optional. Retries with the same key return the same ticket/lease (renewed or re-claimed). */
            idempotency_key?: string;
        };
        ClaimResponseBody: {
            ticket?: components["schemas"]["Ticket"];
            lease?: components["schemas"]["Lease"];
        };
        Lease: {
            ticket_id?: string;
            agent_id?: string;
            token?: string;
            /** Format: date-time */
            expires_at?: string;
            renewable?: boolean;
        };
        RenewLeaseRequest: {
            lease_token: string;
        };
        RenewLeaseResponseBody: {
            /** Format: date-time */
            expires_at?: string;
        };
        TransitionHistory: {
            ticket_id?: string;
            current_state?: string;
            transitions?: components["schemas"]["StateTransitionEntry"][];
        };
        StateTransitionEntry: {
            id?: string;
            from_state?: string;
            to_state?: string;
            trigger?: string;
            actor_id?: string;
            /** @enum {string} */
            actor_type?: "human" | "agent" | "system";
            /** Format: date-time */
            created_at?: string;
        };
        GateCondition: {
            /** @enum {string} */
            type: "github_checks" | "human_approval" | "webhook" | "http_check";
            config?: {
                [key: string]: unknown;
            };
        };
        GateRequirement: {
            /** @enum {string} */
            type: "github_checks" | "human_approval" | "webhook" | "http_check";
            config?: {
                [key: string]: unknown;
            };
        };
        GateRequirementStatus: {
            requirement?: components["schemas"]["GateRequirement"];
            satisfied?: boolean;
            reason?: string;
            /** Format: date-time */
            checked_at?: string;
        };
        WorkflowPhase: {
            id: string;
            name: string;
            /** @enum {string} */
            type: "agent" | "external" | "gate" | "action" | "manual" | "automated" | "deploy" | "observe";
            description?: string;
            config?: {
                [key: string]: unknown;
            };
            on_failure?: string;
        };
        WorkflowDefinition: {
            id?: string;
            /** @enum {string} */
            scope?: "system" | "org" | "project";
            scope_id?: string;
            name: string;
            description?: string;
            version?: number;
            phases: components["schemas"]["WorkflowPhase"][];
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        WorkflowPosition: {
            workflow_id?: string;
            workflow_name?: string;
            current_phase?: components["schemas"]["WorkflowPhase"];
            phase_index?: number;
            total_phases?: number;
            history?: components["schemas"]["PhaseCompletion"][];
        };
        PhaseCompletion: {
            id?: string;
            ticket_id?: string;
            workflow_id?: string;
            phase_id?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
            /** @enum {string} */
            outcome?: "success" | "failed" | "skipped";
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** @description One tracked Claude Code or Codex session. */
        AgentSession: {
            id: string;
            /** @description claude_code or codex */
            harness: string;
            /** @description The harness's own session or thread id */
            external_id: string;
            /** @description interactive, dispatched, automation, or subagent */
            origin: string;
            parent_session_id?: string;
            cwd: string;
            repo: string;
            branch: string;
            model: string;
            reasoning_effort: string;
            title: string;
            first_prompt: string;
            transcript_path: string;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            prompt_count: number;
            tool_call_count: number;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            last_activity_at: string;
            /** Format: date-time */
            ended_at?: string;
            /** @description active, idle, or ended (derived from recency) */
            status: string;
            links: components["schemas"]["SessionLink"][];
            metadata?: {
                [key: string]: unknown;
            };
        };
        SessionLink: {
            session_id: string;
            /** @description pr, linear_issue, ticket, or review */
            kind: string;
            /** @description owner/repo#123, KEY-123, ticket id, or review request id */
            ref: string;
            /** @description inferred, explicit, or dispatch */
            source: string;
            /** Format: date-time */
            created_at: string;
        };
        SessionPrompt: {
            seq: number;
            role: string;
            text: string;
            /** Format: date-time */
            ts: string;
        };
        SessionDetail: {
            session: components["schemas"]["AgentSession"];
            prompts: components["schemas"]["SessionPrompt"][];
            children: components["schemas"]["AgentSession"][];
        };
        SessionListResponse: {
            sessions: components["schemas"]["AgentSession"][];
            total: number;
            limit: number;
            offset: number;
        };
        CreateSessionLinkRequest: {
            /** @enum {string} */
            kind: "pr" | "linear_issue" | "ticket" | "review";
            ref: string;
        };
        SessionCollectorStatus: {
            enabled: boolean;
            claude_dir: string;
            codex_dir: string;
            /** Format: date-time */
            last_run_at?: string;
            last_error?: string;
            /** Format: int64 */
            last_duration_ms: number;
            sessions_total: number;
            by_harness: {
                [key: string]: number;
            };
        };
        ProjectLinearLink: {
            project_id: string;
            linked: boolean;
            linear_project_id?: string;
            linear_project_name?: string;
            linear_project_url?: string;
            team_keys: string[];
            /** Format: date-time */
            synced_at?: string;
            last_error?: string;
            ticket_count: number;
        };
        LinearStatus: {
            enabled: boolean;
            viewer_name?: string;
            viewer_email?: string;
            projects_linked: number;
            tickets_linked: number;
            /** Format: date-time */
            last_run_at?: string;
            last_error?: string;
            /** Format: int64 */
            last_duration_ms: number;
            links: components["schemas"]["ProjectLinearLink"][];
        };
        CodeReviewFinding: {
            id: string;
            attempt: number;
            /** @description P0, P1, P2, or P3 */
            severity: string;
            path: string;
            line: number;
            title: string;
            body: string;
            /** Format: int64 */
            github_comment_id?: number;
            /** @description pending, posted, in_body, withheld, resolved, or outdated */
            status: string;
        };
        CodeReviewRequest: {
            id: string;
            repo: string;
            number: number;
            url: string;
            title: string;
            author: string;
            base_ref?: string;
            head_ref?: string;
            head_sha?: string;
            origin: string;
            recipe?: string;
            harness: string;
            model?: string;
            state: string;
            attempt: number;
            watch: boolean;
            dry_run: boolean;
            verdict: string;
            summary: string;
            review_url?: string;
            my_review_state?: string;
            session_id?: string;
            error?: string;
            /** Format: date-time */
            reviewed_at?: string;
            /** Format: date-time */
            last_checked_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            findings: components["schemas"]["CodeReviewFinding"][];
        };
        CodeReviewListResponse: {
            requests: components["schemas"]["CodeReviewRequest"][];
            total: number;
            limit: number;
            offset: number;
        };
        CreateCodeReviewRequest: {
            /** @description Free text containing GitHub PR URLs or owner/repo#N references */
            text: string;
            dry_run?: boolean;
            watch?: boolean;
            /** @description codex or claude */
            harness?: string;
        };
        FeedbackRound: {
            id: string;
            repo: string;
            number: number;
            url: string;
            title: string;
            head_sha?: string;
            reviewer: string;
            review_state: string;
            /** Format: int64 */
            review_id: number;
            comment_count: number;
            body?: string;
            /** @description new, dispatched, addressed, or ignored */
            state: string;
            ticket_id?: string;
            session_id?: string;
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            submitted_at?: string;
        };
        FeedbackRoundListResponse: {
            rounds: components["schemas"]["FeedbackRound"][];
        };
        SetFeedbackRoundStateRequest: {
            /** @enum {string} */
            state: "new" | "dispatched" | "addressed" | "ignored";
        };
        CodeReviewStatus: {
            enabled: boolean;
            login?: string;
            harness: string;
            publish: boolean;
            watch_requested: boolean;
            watch_authored: boolean;
            /** Format: date-time */
            last_queue_run_at?: string;
            /** Format: date-time */
            last_poll_at?: string;
            last_error?: string;
            active: number;
            queued: number;
            watching: number;
            new_feedback: number;
            reviews_posted: number;
            max_concurrent: number;
            repo_root?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMeStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeStats"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetMeStatsHistory: {
        parameters: {
            query?: {
                /** @description Number of days (default 14, max 90). */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeStatsHistory"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListProjectsByOrg: {
        parameters: {
            query?: {
                /** @description Filter by project status; default active. */
                status?: "active" | "closed" | "all";
            };
            header?: never;
            path: {
                orgID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    CreateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    UpdateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Bad request (e.g. invalid status) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListWorkStreams: {
        parameters: {
            query?: {
                /** @description Filter by status; default active. */
                status?: "active" | "closed" | "all";
            };
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkStream"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateWorkStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkStreamRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkStream"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetWorkStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
                workStreamID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkStream"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    UpdateWorkStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
                workStreamID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkStreamRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkStream"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListTickets: {
        parameters: {
            query?: {
                /** @description Filter by work stream. */
                work_stream_id?: string;
                /** @description Filter by ticket state. */
                state?: "draft" | "planning" | "awaiting_input" | "executing" | "awaiting_validation" | "validated" | "closed";
            };
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    UpdateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateTicketRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListPendingReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingReviewsResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetTrace: {
        parameters: {
            query?: {
                /** @description Maximum number of steps to return (descending order). Omit for all steps. */
                limit?: number;
                /** @description Number of steps to skip (for pagination). */
                offset?: number;
            };
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionTrace"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    LogStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogStepRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request (e.g. missing lease_token or step.type) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetTransitions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionHistory"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    TransitionTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request (e.g. trigger required) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListEscalations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Escalation"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ResolveEscalation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
                escalationID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveEscalationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ClaimTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResponseBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    RenewLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewLeaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenewLeaseResponseBody"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ReleaseLease: {
        parameters: {
            query?: {
                lease_token?: string;
            };
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    lease_token?: string;
                };
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    PostGateCallback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    metadata?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Gate condition marked as satisfied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        ticket_id?: string;
                        phase_id?: string;
                    };
                };
            };
            /** @description Token not found or expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListSessions: {
        parameters: {
            query?: {
                harness?: "claude_code" | "codex";
                origin?: "interactive" | "dispatched" | "automation" | "subagent";
                /** @description Repository as owner/name or bare name. */
                repo?: string;
                branch?: string;
                status?: "active" | "idle" | "ended";
                /** @description Full-text search over prompts, title, repo, branch, and linked refs. */
                q?: string;
                since?: string;
                /** @description Only sessions linked to this ref (owner/repo#N, KEY-N, ticket id). */
                ref?: string;
                include_subagents?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetSessionCollectorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCollectorStatus"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateSessionLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionLinkRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionLink"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetLinearStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinearStatus"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetProjectLinearLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLinearLink"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    SyncProjectLinear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLinearLink"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListCodeReviews: {
        parameters: {
            query?: {
                state?: string;
                repo?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeReviewListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateCodeReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCodeReviewRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeReviewListResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetCodeReviewStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeReviewStatus"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListFeedbackRounds: {
        parameters: {
            query?: {
                state?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRoundListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    SetFeedbackRoundState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetFeedbackRoundStateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRound"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    AddressFeedbackRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRound"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetCodeReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeReviewRequest"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    RerunCodeReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeReviewRequest"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CloseCodeReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeReviewRequest"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
}
