package report

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

func writeTickets(b *strings.Builder, heading string, lines []TicketLine) {
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(b, "\n**%s (%d)**\n", heading, len(lines))
	for _, l := range lines {
		if l.URL != "" {
			fmt.Fprintf(b, "- [%s](%s) %s\n", l.Identifier, l.URL, l.Title)
		} else {
			fmt.Fprintf(b, "- %s %s\n", l.Identifier, l.Title)
		}
	}
}

func writePRs(b *strings.Builder, heading string, lines []PRLine) {
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(b, "\n**%s (%d)**\n", heading, len(lines))
	for _, l := range lines {
		fmt.Fprintf(b, "- [%s#%d](%s) %s\n", shortRepo(l.Repo), l.Number, l.URL, l.Title)
	}
}

func writeActivity(b *strings.Builder, lines []HarnessLine) {
	if len(lines) == 0 {
		return
	}
	b.WriteString("\n**Agent activity**\n")
	for _, a := range lines {
		fmt.Fprintf(b, "- %s: %d session%s, %s in / %s out tokens\n", harnessLabel(a.Harness), a.Sessions, plural(a.Sessions), compact(a.TokensIn), compact(a.TokensOut))
	}
}

// RenderProjectUpdate produces the Linear project update body: delta first, then state.
func RenderProjectUpdate(d ProjectData) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## Update — %s\n", d.Until.Format("Jan 2"))
	fmt.Fprintf(&b, "_Since %s._\n", d.Since.Format("Jan 2, 15:04"))
	total := len(d.Done) + len(d.MergedPRs)
	if total == 0 {
		b.WriteString("\nNothing merged or closed in this window.\n")
	}
	writeTickets(&b, "Done", d.Done)
	writePRs(&b, "Merged", d.MergedPRs)
	writeTickets(&b, "In review", d.InReview)
	writePRs(&b, "Open PRs", d.OpenPRs)
	writeTickets(&b, "In progress", d.InProgress)
	writeTickets(&b, "Blocked or waiting on a decision", d.Blocked)
	writePRs(&b, "Review feedback awaiting a response", d.Feedback)
	writeTickets(&b, "New since last update", d.New)
	writeActivity(&b, d.Activity)
	b.WriteString("\n_Posted by Flywheel._\n")
	return b.String()
}

// SuggestHealth derives project health from the delta: blocked work or unanswered
// change requests mean at risk; nothing moving for a full window means off track.
func SuggestHealth(d ProjectData, fallback string) string {
	if len(d.Blocked) > 0 || len(d.Feedback) > 0 {
		return HealthAtRisk
	}
	if len(d.Done)+len(d.MergedPRs)+len(d.InReview)+len(d.InProgress)+len(d.OpenPRs) == 0 && d.Until.Sub(d.Since) >= 7*24*time.Hour {
		return HealthOffTrack
	}
	if fallback == "" {
		return HealthOnTrack
	}
	return fallback
}

// RenderWeeklyRoundup produces the rolling-document section for one week.
func RenderWeeklyRoundup(w WeekData) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## Week of %s\n", w.Start.Format("Jan 2, 2006"))
	fmt.Fprintf(&b, "_%s – %s_\n", w.Start.Format("Mon Jan 2"), w.End.Add(-time.Second).Format("Mon Jan 2"))
	if len(w.MergedPRs) > 0 {
		fmt.Fprintf(&b, "\n### Shipped (%d PRs merged)\n", len(w.MergedPRs))
		fmt.Fprintf(&b, "| Repo | PR | Title | Merged |\n|---|---|---|---|\n")
		for _, p := range w.MergedPRs {
			fmt.Fprintf(&b, "| %s | [#%d](%s) | %s | %s |\n", shortRepo(p.Repo), p.Number, p.URL, escapePipes(p.Title), p.When.Format("Mon"))
		}
	} else {
		b.WriteString("\n### Shipped\nNo PRs merged this week.\n")
	}
	for _, p := range w.Projects {
		if len(p.Done)+len(p.InReview)+len(p.InProgress)+len(p.Blocked)+len(p.New) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n### %s\n", p.ProjectName)
		b.WriteString("| Ticket | Title | Status |\n|---|---|---|\n")
		rows := []struct {
			status string
			lines  []TicketLine
		}{{"Done", p.Done}, {"In review", p.InReview}, {"In progress", p.InProgress}, {"Blocked", p.Blocked}, {"New", p.New}}
		for _, r := range rows {
			for _, l := range r.lines {
				id := l.Identifier
				if l.URL != "" {
					id = fmt.Sprintf("[%s](%s)", l.Identifier, l.URL)
				}
				fmt.Fprintf(&b, "| %s | %s | %s |\n", id, escapePipes(l.Title), r.status)
			}
		}
	}
	if len(w.Activity) > 0 {
		b.WriteString("\n### Agent activity\n")
		for _, a := range w.Activity {
			fmt.Fprintf(&b, "- %s: %d session%s, %s in / %s out tokens\n", harnessLabel(a.Harness), a.Sessions, plural(a.Sessions), compact(a.TokensIn), compact(a.TokensOut))
		}
	}
	b.WriteString("\n_Generated by Flywheel._\n")
	return b.String()
}

// PrependSection inserts a new week at the top of a rolling document, replacing an
// existing section with the same heading.
func PrependSection(existing, section string) string {
	heading := strings.SplitN(section, "\n", 2)[0]
	existing = strings.TrimSpace(existing)
	if idx := strings.Index(existing, heading); idx >= 0 {
		rest := existing[idx+len(heading):]
		if next := strings.Index(rest, "\n## "); next >= 0 {
			existing = strings.TrimSpace(existing[:idx] + rest[next+1:])
		} else {
			existing = strings.TrimSpace(existing[:idx])
		}
	}
	if existing == "" {
		return strings.TrimSpace(section) + "\n"
	}
	// Keep a leading title (a line starting with "# ") in place.
	if strings.HasPrefix(existing, "# ") {
		if nl := strings.Index(existing, "\n"); nl >= 0 {
			return existing[:nl+1] + "\n" + strings.TrimSpace(section) + "\n\n" + strings.TrimSpace(existing[nl+1:]) + "\n"
		}
		return existing + "\n\n" + strings.TrimSpace(section) + "\n"
	}
	return strings.TrimSpace(section) + "\n\n" + existing + "\n"
}

// WeekWindow returns [Monday 00:00, next Monday 00:00) local time for the week containing t.
func WeekWindow(t time.Time) (time.Time, time.Time) {
	t = t.Local()
	weekday := int(t.Weekday())
	if weekday == 0 {
		weekday = 7
	}
	start := time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, t.Location()).AddDate(0, 0, -(weekday - 1))
	return start, start.AddDate(0, 0, 7)
}

func sortPRs(prs []PRLine) {
	sort.Slice(prs, func(i, j int) bool {
		if prs[i].Repo != prs[j].Repo {
			return prs[i].Repo < prs[j].Repo
		}
		return prs[i].Number < prs[j].Number
	})
}

func shortRepo(repo string) string {
	if i := strings.LastIndex(repo, "/"); i >= 0 {
		return repo[i+1:]
	}
	return repo
}

func harnessLabel(h string) string {
	switch h {
	case "claude_code":
		return "Claude Code"
	case "codex":
		return "Codex"
	}
	return h
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

func compact(n int64) string {
	switch {
	case n >= 1_000_000_000:
		return fmt.Sprintf("%.1fB", float64(n)/1e9)
	case n >= 1_000_000:
		return fmt.Sprintf("%.1fM", float64(n)/1e6)
	case n >= 1_000:
		return fmt.Sprintf("%.0fk", float64(n)/1e3)
	}
	return fmt.Sprintf("%d", n)
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
