#!/usr/bin/env bash
# dev-preflight.sh — Verify (and where possible fix) local dev prerequisites.
# Called by `make dev` before starting anything.
set -uo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
RESET='\033[0m'

ok()   { printf "${GREEN}[ok]${RESET}  %b\n" "$1"; }
warn() { printf "${YELLOW}[!!]${RESET}  %b\n" "$1"; }
fail() { printf "${RED}[FAIL]${RESET} %b\n" "$1"; }

errors=0

# ── 1. Docker ──────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  fail "docker is not installed."
  echo "     Install Docker Desktop: https://docs.docker.com/desktop/install/mac-install/"
  errors=$((errors + 1))
elif ! docker info &>/dev/null 2>&1; then
  fail "Docker daemon is not running. Start Docker Desktop and retry."
  errors=$((errors + 1))
else
  ok "docker"
fi

# ── 2. golang-migrate ─────────────────────────────────────────────────────
if ! command -v migrate &>/dev/null; then
  warn "golang-migrate (migrate) not found. Attempting install via brew..."
  if command -v brew &>/dev/null; then
    if brew install golang-migrate; then
      ok "golang-migrate installed"
    else
      fail "Failed to install golang-migrate."
      echo "     Manual install: brew install golang-migrate"
      errors=$((errors + 1))
    fi
  else
    fail "golang-migrate not found and brew is not available."
    echo "     Install: brew install golang-migrate"
    errors=$((errors + 1))
  fi
else
  ok "golang-migrate"
fi

# ── 3. nvm + Node 22 ──────────────────────────────────────────────────────
# nvm is a shell function loaded via source. Its auto-use feature can return
# non-zero when the .nvmrc version isn't installed yet, so we must tolerate that.
_source_nvm() {
  if command -v brew &>/dev/null; then
    local brew_nvm
    brew_nvm="$(brew --prefix 2>/dev/null)/opt/nvm/nvm.sh"
    if [[ -s "$brew_nvm" ]]; then
      export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
      mkdir -p "$NVM_DIR"
      # shellcheck disable=SC1090
      source "$brew_nvm" || true
      return 0
    fi
  fi
  export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
  if [[ -s "$NVM_DIR/nvm.sh" ]]; then
    # shellcheck disable=SC1091
    source "$NVM_DIR/nvm.sh" || true
    return 0
  fi
  return 1
}

nvm_available=false
if _source_nvm; then
  nvm_available=true
else
  warn "nvm not found. Attempting install via brew..."
  if command -v brew &>/dev/null; then
    if brew install nvm 2>/dev/null; then
      if _source_nvm; then
        nvm_available=true
      fi
    fi
  fi
  if [[ "$nvm_available" != "true" ]]; then
    fail "nvm is not installed and could not be auto-installed."
    echo "     Install: https://github.com/nvm-sh/nvm#installing-and-updating"
    errors=$((errors + 1))
  fi
fi

if [[ "$nvm_available" == "true" ]]; then
  REQUIRED_NODE=22
  CURRENT_NODE=$(node --version 2>/dev/null | sed 's/^v//' | cut -d. -f1 || echo "")
  if [[ "$CURRENT_NODE" != "$REQUIRED_NODE" ]]; then
    warn "Node $REQUIRED_NODE required (current: ${CURRENT_NODE:-none}). Running nvm install $REQUIRED_NODE..."
    if nvm install "$REQUIRED_NODE" && nvm use "$REQUIRED_NODE"; then
      ok "Node $(node --version)"
    else
      fail "Failed to install Node $REQUIRED_NODE via nvm."
      errors=$((errors + 1))
    fi
  else
    ok "Node $(node --version)"
  fi
fi

# ── 4. Go ──────────────────────────────────────────────────────────────────
if ! command -v go &>/dev/null; then
  fail "go is not installed."
  echo "     Install: https://go.dev/dl/ or brew install go"
  errors=$((errors + 1))
else
  ok "go $(go version | awk '{print $3}' | sed 's/go//')"
fi

# ── 5. .env ───────────────────────────────────────────────────────────────
if [[ ! -f .env ]]; then
  warn ".env not found. Creating from defaults for local dev..."
  cat > .env <<'ENVEOF'
# Generated by dev-preflight.sh — local development defaults.
# Adjust as needed; this file is .gitignored.

PORT=8090
DATABASE_URL=postgres://flywheel:flywheel@localhost:5439/flywheel?sslmode=disable
REDIS_URL=redis://localhost:6389/0

# The local UI opens directly; a callback signing key is generated when empty.
JWT_SECRET=
ENVEOF
  ok ".env created with local dev defaults (localhost ports)."
else
  ok ".env exists"
fi

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
if [[ $errors -gt 0 ]]; then
  fail "${BOLD}${errors} prerequisite(s) missing. Fix the issues above and re-run make dev.${RESET}"
  exit 1
else
  ok "${BOLD}All prerequisites satisfied.${RESET}"
fi
